# Site settings
title: DiscourseDB - Bridging discourse across platforms
tag_text: DiscourseDB
description: DiscourseDB is a framework for representing discourse from multiple platforms in a uniform representation.

# Build settings
markdown: kramdown

exclude: ["README.md"]
